# Generated by Django 4.2.11 on 2024-03-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ('-updated_at',)},
        ),
    ]
