# Generated by Django 4.2.11 on 2024-03-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0002_alter_comment_options_alter_rank_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='big_image',
            field=models.ImageField(default='hospital_images/default_big_image.jpg', null=True, upload_to='hospital_images'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='small_image',
            field=models.ImageField(default='hospital_images/default_mini_image.jpg', null=True, upload_to='hospital_images'),
        ),
    ]
