# Generated by Django 4.2.11 on 2024-04-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0003_alter_hospital_big_image_alter_hospital_small_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_on_main',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='category',
        ),
        migrations.AddField(
            model_name='hospital',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='our_service.category'),
        ),
    ]
