# Generated by Django 4.2.11 on 2024-04-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0004_hospital_is_on_main_remove_hospital_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='category',
            field=models.ManyToManyField(blank=True, to='our_service.category'),
        ),
    ]
